"""
Tests for activealchemy/mixins.py
"""
import asyncio
import uuid
from datetime import datetime, timedelta

import pytest

# Use the setup fixture defined in async/conftest.py
# pytestmark = pytest.mark.usefixtures("setup_mixin_tests")


@pytest.mark.asyncio
async def test_pkmixin_id_creation(setup_mixin_tests, mock_pk_model_class):
    """Test that PKMixin creates a UUID id."""
    instance = mock_pk_model_class(name="pk_test")
    # ID should be generated by default_factory on init
    assert isinstance(instance.id, uuid.UUID)
    # Save to ensure server_default also works (though harder to test exact value)
    await instance.save(commit=True)

    assert isinstance(instance.id, uuid.UUID)


@pytest.mark.asyncio
async def test_pkmixin_find(setup_mixin_tests, mock_pk_model_class):
    """Test the find classmethod of PKMixin."""
    instance = await mock_pk_model_class(name="find_test").save(commit=True)
    found_instance = await mock_pk_model_class.find(instance.id)
    assert found_instance is not None
    assert found_instance.id == instance.id
    assert found_instance.name == "find_test"

    # Test find non-existent
    non_existent_uuid = uuid.uuid4()
    not_found_instance = await mock_pk_model_class.find(non_existent_uuid)
    assert not_found_instance is None


@pytest.mark.asyncio
async def test_updatemixin_timestamps(setup_mixin_tests, mock_update_model_class, mock_combined_model_class):
    """Test that UpdateMixin adds and manages timestamps."""
    # start_time = datetime.now(UTC) # Removed unused variable
    await asyncio.sleep(0.01) # Ensure time progresses slightly

    instance = mock_combined_model_class(name="timestamp_test")

    # Timestamps should not be set before save
    # Note: MappedAsDataclass might initialize them depending on exact setup,
    # but they should be overwritten by server_default on save.
    # Let's check after save.
    async with await mock_update_model_class.get_session() as session:
        instance = await instance.save(commit=True, session=session)


        await asyncio.sleep(0.01)
        # end_time = datetime.now(UTC) # Removed unused variable

        assert isinstance(instance.created_at, datetime)
        assert isinstance(instance.updated_at, datetime)
        # Initially, created_at and updated_at should be very close
        assert abs(instance.updated_at - instance.created_at) < timedelta(seconds=1)

        # Test onupdate
        created_at_before_update = instance.created_at
        updated_at_before_update = instance.updated_at

        await asyncio.sleep(0.05) # Ensure updated_at changes significantly
        instance.name = "timestamp_test_updated"
        instance = await instance.save(commit=True, session=session)


        assert instance.created_at == created_at_before_update # created_at should not change
        assert instance.updated_at > updated_at_before_update
        assert instance.updated_at > instance.created_at
        #assert instance.updated_at > start_time + timedelta(seconds=0.05)


@pytest.mark.asyncio
async def test_updatemixin_queries(setup_mixin_tests, mock_combined_model_class):
    """Test timestamp-baed query methods of UpdateMixin."""
    Model = mock_combined_model_class
    async with await mock_combined_model_class.get_session() as session:
    # Create instances with varying timestamps
        instance1 = await Model(name="q_old").save(commit=True, session=session)
        await asyncio.sleep(0.05)
        # time_after_1 = datetime.now(UTC) # Unused
        await asyncio.sleep(0.05)
        instance2 = await Model(name="q_mid").save(commit=True, session=session)
        await asyncio.sleep(0.05)
        instance3 = await Model(name="q_new").save(commit=True, session=session)
        await asyncio.sleep(0.05)
        # time_after_3 = datetime.now(UTC) # Unused
        await asyncio.sleep(0.05)

        # Update instance2
        instance2.name = "q_mid_updated"
        instance2 = await instance2.save(commit=True, session=session)
        await asyncio.sleep(0.05)
    # time_after_update = datetime.now(UTC) # Unused


    # --- Test last_created ---
        last_created = await Model.last_created()
        assert last_created is not None
        assert last_created.id == instance3.id # instance3 was created last

        # --- Test first_created ---
        first_created = await Model.first_created()
        assert first_created is not None
        assert first_created.id == instance1.id # instance1 was created first

        # --- Test last_modified ---
        last_modified = await Model.last_modified()
        assert last_modified is not None
        # instance2 was updated most recently
        assert last_modified.id == instance2.id

        # --- Test get_since ---
        # Get records modified after instance1 was created
        since_time1 = instance1.updated_at # Use updated_at as modification time
        modified_since_1 = await Model.get_since(since_time1)
        # Should include instance2 (updated) and instance3 (created)
        assert len(modified_since_1) == 2
        modified_ids = {m.id for m in modified_since_1}
        assert instance2.id in modified_ids
        assert instance3.id in modified_ids

        # Get records modified after instance3 was created but before instance2 was updated
        since_time3 = instance3.updated_at
        modified_since_3 = await Model.get_since(since_time3)
         # Should include only instance2 (which was updated after instance3 creation)
        assert len(modified_since_3) == 1
        assert modified_since_3[0].id == instance2.id

        # Get records modified after instance2 was updated
        since_update_time = instance2.updated_at
        modified_since_update = await Model.get_since(since_update_time)
        # Should include none, as nothing was modified after instance2's update
        assert len(modified_since_update) == 0
